spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /PROJECT-SERVICE/v3/api-docs
        name: PROJECT-SERVICE
      - url: /TASK-SERVICE/v3/api-docs
        name: TASK-SERVICE
      - url: /RESOURCE-SERVICE/v3/api-docs
        name: RESOURCE-SERVICE
      - url: /USER-SERVICE/v3/api-docs
        name: USER-SERVICE

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true