spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://taskdb:3306/constructxpert_task_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    table: flyway_schema_history
    enabled: true
    url: jdbc:mysql://taskdb:3306/constructxpert_task_db
    user: root
    password: 1234
  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: TASK-SERVICE doc
    version: 1.0.0
    url: http://localhost:9191/TASK-SERVICE